# Generated by Django 2.2 on 2021-01-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('fnacimiento', models.DateField(auto_now=True, verbose_name='Fecha de nacimiento')),
                ('obra_social', models.BooleanField(default=True, verbose_name='Activo/Desactivo')),
            ],
            options={
                'ordering': ['nombres'],
            },
        ),
    ]
