# Generated by Django 2.2 on 2021-02-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_paciente_h_clinica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento_tipo', models.CharField(max_length=200)),
                ('dni_numero', models.IntegerField(blank=True, max_length=16, null=True)),
            ],
            options={
                'ordering': ['dni_numero'],
            },
        ),
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=200)),
                ('localidad', models.CharField(max_length=200)),
                ('telefono', models.IntegerField(max_length=26)),
                ('correo', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Localizacion',
                'verbose_name_plural': 'Localizaciones',
                'ordering': ['localidad'],
            },
        ),
    ]
