# Generated by Django 2.2 on 2021-03-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_auto_20210310_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['documento_tipo']},
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='documento',
            new_name='documento_type',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='dni_numero',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='localizacion',
        ),
        migrations.AddField(
            model_name='paciente',
            name='correo',
            field=models.EmailField(default='dni', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(default='san', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='documento_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='localidad',
            field=models.CharField(default='miguel', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Localizacion',
        ),
    ]
