# Generated by Django 2.2 on 2021-03-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_auto_20210310_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='obra_social',
            field=models.BooleanField(default=True, verbose_name='Con Obra Social/Sin Obra Social'),
        ),
    ]
