# Generated by Django 2.2 on 2021-03-11 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_delete_registro'),
        ('paciente', '0008_auto_20210311_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='altura',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='enfermedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Enfermedad'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fil_glomerular',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='frec_cardiaca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fuma',
            field=models.BooleanField(default=False, verbose_name='Fuma'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='hemog_glic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='indece_masa_corp',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Medicacion'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='peso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='pres_arterial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='saturacion_oxig',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='temperatura',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='vacunacion',
            field=models.BooleanField(default=True, verbose_name='Ultimo refuerzo'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='vef1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
