# Generated by Django 2.2 on 2021-03-11 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0009_auto_20210311_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='indece_masa_corp',
            new_name='indice_masa_corp',
        ),
    ]
