# Generated by Django 2.2 on 2021-03-11 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0011_auto_20210311_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='h_clinica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TSC', to='historiaclinica.H_clinica'),
        ),
    ]
