# Generated by Django 2.2 on 2021-03-11 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0012_auto_20210311_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='h_clinica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='historiaclinica.H_clinica'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='hemog_glic',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hemoglobina Glicosilada'),
        ),
    ]
