# Generated by Django 2.2 on 2021-02-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_registro_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='altura',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
