# Generated by Django 2.2 on 2021-02-02 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20210131_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Enfermedad',
                'verbose_name_plural': 'Enfermedades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Medicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('nombres_drogas', models.CharField(blank=True, max_length=100, null=True)),
                ('posologia', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Medicacion',
                'verbose_name_plural': 'Medicaciones',
                'ordering': ['marca'],
            },
        ),
        migrations.AddField(
            model_name='registro',
            name='enfermedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Enfermedad'),
        ),
        migrations.AddField(
            model_name='registro',
            name='medicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Medicacion'),
        ),
    ]
