# Generated by Django 2.2 on 2021-03-11 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20210202_2056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
